services:
  database:
    image: postgres:15.4
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:24.0.4
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt

volumes:
  database-data:
  keycloak-data:
